import { useSession, signIn, signOut } from "next-auth/react"
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Dashboard() {
  const { data: session } = useSession()
  if(session) {
    return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
         <div className="w-3/4 mx-auto flex place-items-center">
           <h1 className="text-3xl font-bold">
              Data Integrated Interview Test Answers
            </h1>
         </div>
      </main>
    </>
  )
  }

  return (
    <div>
      <h3>You are not signed in</h3>
      <button onClick={() => signIn()}>Sign in</button>
    </div>
  )
}
